language: python
python:
  - "3.5"
cache: pip
before_install:
  - pip install coveralls
install:
  - pip install -r requirements.txt
  script:
    - coverage run test_auth.py
    - coverage run test_lecturer.py
    - coverage run test_students.py
 after_success:
  - codecov
