language: python
python:
 - "3.5"
cache: pip
before_install:
 - pip install coveralls
install:
 - pip install -r requirements.txt
script:
 - python3 -m venv venv
 - coverage run tests/test_lecturer.py
 - coverage run tests/test_students.py
after_success:
 - codecov
