dist: xenial
language: python
python:
  - "3.7"
cache: pip
services:
 - mysql
before_install:
 - pip install coveralls
install:
 - pip install -r requirements.txt
script: 
 - pip install mysql-connector-python-rf
 - python3 -m venv venv
 - . venv/bin/activate
 - pip install -r requirements.txt
 - coverage run test_app.py
after_success:
 - codecov
