dist: xenial
language: python
python:
  - "3.7"
cache: pip
services:
 - mysql
before_install:
 - pip install pytest
 - pip install pytest-cov
 - pip install coveralls
install:
 - pip install -r requirements.txt
script: 
 - pip install mysql-connector-python-rf
 - python3 -m venv venv
 - . venv/bin/activate
 - pip install -r requirements.txt
 - coverage run --source=mypkg -m pytest tests/
after_success:
 - codecov
