dist: xenial
language: python
python:
  - "3.7"
cache: pip
services:
 - mysql
before_install:
 - pip install coveralls
install:
 - pip install -r requirements.txt
script: 
 - pip install --egg http://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.4.zip
 - python3 -m venv venv
 - . venv/bin/activate
 - ls
 - pip install -r requirements.txt
 - cd app
 - ls
 - pytest
after_success:
 - codecov
